name: Deploy to IPFS via Pinata

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: npm install -g ipfs-http-client

      - name: Deploy to IPFS
        run: |
          npm install -g pinata-cli
          pinata-cli --pinataApiKey=${{ secrets.PINATA_API_KEY }} --pinataSecretApiKey=${{ secrets.PINATA_SECRET_API_KEY }} pin ./ --name "My IPFS Website"
